### PR TITLE
With Flutter SDK 3.16.0-0.1.pre maybeDispatchObjectCreation proxy implementation is not needed any more

### PR DESCRIPTION
**Pull request by MrCsabaToth**
Ref #34
Also undo the Github CI (beta -> stable)

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
Hmmm, test failed

**Comment by simonste** [comment]
I ran into this issue, because i am using the latest github version.

@DavBfr: Please undo #34 on master

**Comment by MrCsabaToth** [comment]
Fixes #34

**Comment by DavBfr** [comment]
Done.

**Pull request closed without merging**
