### PR TITLE
Fixes #9 by adding vertical alignment

### LINKED ISSUE #9: Slider is too short while it is in a row with the label
I'd propose to have the label and the slider laid out in a `Column` instead of the `Row`. Otherwise the slider is way too narrow for example to set a weight or age of a person.

### PR DESCRIPTION
**Pull request by MrCsabaToth**
The title and the value labeling (previously trailing) stays in line. The slider is aligned below them if the direction is Axis.vertical. The default direction stays horizontal preserving the existing scrollbars. The build code was different enough that there are two larger statements. There's also an example added. There wasn't any code documentation so I haven't fiddled with anything on that note.
I tested the cases when the title is empty, or the value labeling is empty: in that case whichever is present it is aligned to the left.

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
I'm happy to make any changes requested.

**Comment by MrCsabaToth** [comment]
GitHub didn't pick this PR up at the issue ticket. Let's try again: Fixes #9

**Comment by DavBfr** [comment]
Can you update the Changelog and set the pubspec version to 2.4.0?

**Comment by DavBfr** [comment]
Thanks!

**Pull request merged**
